package ch.epfl.javions.adsb;

public enum MessageType {
    UNKNOWN,
    AIRCRAFT_IDENTIFICATION,
    SURFACE_POSITION,
    AIRBORNE_POSITION,
    AIRBORNE_VELOCITIES,
    AIRCRAFT_STATUS,
    TARGET_STATE,
    AIRCRAFT_OPERATION_STATUS
}
