package ch.epfl.javions.adsb;

public enum WakeVortexCategory {
    UNKNOWN,
    SURFACE_EMERGENCY_VEHICLE,
    SURFACE_SERVICE_VEHICLE,
    GROUND_OBSTRUCTION,
    GLIDER,
    LIGHTER_THAN_AIR,
    PARACHUTIST,
    ULTRALIGHT,
    UNMANNED_AERIAL_VEHICLE,
    SPACE_OR_TRANSATMOSPHERIC_VEHICLE,
    LIGHT,
    MEDIUM_1,
    MEDIUM_2,
    HIGH_VORTEX_AIRCRAFT,
    HEAVY,
    HIGH_PERFORMANCE_HIGH_SPEED,
    ROTORCRAFT
}
